spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DATABASE_URL}
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    open-in-view: false

  application:
    name: atm-reporting-service
  main:
    banner-mode: off
